---
title: "parse_barttovik"
author: "tw"
date: "2026-06-18"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(tictoc)
library(bigrquery)
library(dplyr)
library(stringr) #str_detect, str_sub
library(tidyr) #replacena
options(scipen = 999)
library(readr) #readr::read_tsv
library(collapse) #fill in missing names where claim outside of encounter
library(purrr) #to read all tabs
library(readxl) #read xl
library(openxlsx) #create xl w sheets
library(fuzzyjoin) # for join where df$key in df2$key-3,-2-1,+1
library(data.table) #faster than fuzzyjoin
# options(gargle_oob_default = TRUE) #does this help cache?
# options(connectionObserver = NULL) #doesnt work

write_list_to_xlsx <- function(x, sheet_names, file_name) {
  # Basic checks
  if (length(x) != length(sheet_names)) {
    stop("Length of x and sheet_names must match.")
  }
  wb <- createWorkbook()
  for (i in seq_along(x)) {
    df <- x[[i]]
    sheet <- sheet_names[[i]]
    addWorksheet(wb, sheet)
    # Write as Excel table
    writeDataTable(
      wb, sheet, df,
      startRow = 1, startCol = 1,
      tableStyle = "None" #TableStyleMedium2 is blue+white
    )
    # Auto column widths
    setColWidths(
      wb, sheet,
      cols = 1:ncol(df),
      widths = "auto"
    )
  }
  saveWorkbook(wb, file_name, overwrite = TRUE)
}
```

#drafts

```{r}
b0 = read_csv('bartovik//0 inputs//paste 2003 drafted seasons since 2008.csv'
              ,skip=77)

b1 = b0 %>% 
  #split would work but Sep issue
  # seperate(`...30`, into = c('') %>% ) %>% 
  mutate(
     height = case_when(
 `...4` == 'Jun-00' ~ '6-0'
 ,`...4` == 'Jul-00' ~ '7-0'
 ,str_detect(`...4`
            ,"\\d+-[A-Za-z]{3}$") ~ paste(
                                  match(str_extract(`...4`, "[A-Za-z]{3}$"), month.abb),
                                        str_extract(`...4`, "^\\d+"),
                                        sep = "-"
                                          )
            ,TRUE ~ as.character(`...4`))
    ,Dunks = if_else(
      str_detect(Dunks, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(Dunks, "[A-Za-z]{3}$"), month.abb),
        str_extract(Dunks, "^\\d+"),
        sep = "-"
        ),Dunks)
   ,`close_2P` =  if_else(
      str_detect(`...30`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`...30`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`...30`, "^\\d+"),
        sep = "-"
        ),`...30`)
   ,`far_2P` =  if_else(
      str_detect(str_trim(`...32`), "^(\\d+-[A-Za-z]{3}|[A-Za-z]{3}-\\d+)$"),
      paste(
        match(str_extract(`...32`, "[A-Za-z]{3}"), month.abb),
        str_extract(`...32`, "\\d+"),
        sep = "-"
        ),`...32`)
   ,FT =  if_else(
      str_detect(`...34`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`...34`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`...34`, "^\\d+"),
        sep = "-"
        ),`...34`)
   ,`2P` = if_else(
      str_detect(`...36`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`...36`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`...36`, "^\\d+"),
        sep = "-"
        ),`...36`)
   ,`3P` = if_else(
     #if find #-3letters OR 3letters-#
      str_detect(str_trim(`3P/100`), "^(\\d+-[A-Za-z]{3}|[A-Za-z]{3}-\\d+)$"),
      paste(
        #get the Jan, then switch it with 1
        match(str_extract(`3P/100`, "[A-Za-z]{3}"), month.abb),
        #get the digit or 2
        str_extract(`3P/100`, "\\d+"),
        sep = "-"
      ),`3P/100`)
        ) %>% 
  separate(Dunks, into = c('Dunks_m', 'Dunks_a'),sep='-') %>% 
separate(`2P`, into = c('2PM', '2PA'),sep='-') %>% 
separate(`close_2P`, into = c('close_2PM', 'close_2PA'),sep='-')  %>% 
separate(`far_2P`, into = c('far_2PM', 'far_2PA'),sep='-') %>% 
separate(`FT`, into = c('FTM', 'FTA'),sep='-') %>% 
separate(`3P`, into = c('3PM', '3PA'),sep='-') %>% 
  select(-c('...4', '...30', '...32', '...34', '...36', '3P/100')) %>% 
  rename('3P/100'='3PR', '3PR'='...38')

b2 = b1 %>% 
  rename(class = Player, Player='...5') %>% 
  select(-Year) %>% 
  mutate(across(c(28:Reb, close_2PM:far_2PA), as.numeric)) %>% 
  separate(Player, into = c('player', 'stats_yr'),sep='\\(') %>% 
  mutate(
    stats_yr = sub("\\)", "", stats_yr)
    ,player = str_trim(player)
    ,stock_pct = Blk+Stl
   ,`2P_pct` = `2PM`/`2PA`
   ,close_2P_pct = close_2PM/close_2PA
   ,far_2P_pct = far_2PM/far_2PA
   ,`3P_pct` = `3PM`/`3PA`
     ,`FT_pct` = `FTM`/`FTA`
         ) %>% 
  select(Rk, 
         ,stats_yr=Pts
         ,player, class, Team ,Conf
         , Pick, height,Role,G
         ,9:20
         , Ast_pct = 'Ast...22'
         , 22:25, stock_pct, 'FC/40'
         ,'2PM','2PA', '2P_pct'
         ,'Dunks_m',
         ,'close_2PM','close_2PA', 'close_2P_pct'
         ,'far_2PM','far_2PA', 'far_2P_pct'
         ,'3PM','3PA', '3P_pct'
         ,'FTM','FTA', 'FT_pct'
         ,'3PR', '3P/100'
         , Pts=Reb, Ast='Ast...43', Reb = '...42'
         )

b3_yrs = b2 %>% 
  group_by(player, Pick, height) %>% 
  mutate(draft_yr = max(stats_yr)) %>% 
  ungroup() %>% 
  relocate(draft_yr, .before=Pick) %>% relocate(stats_yr, .before=G)

writexl::write_xlsx(b3_yrs, 'bartovik\\1 outputs\\torvik cleaned.xlsx')

```

#26 prospects

```{r}
# p0 = readxl::read_excel('bartovik//0 inputs//paste 2003 drafted seasons since 2008.xlsx'
#               ,skip=79
#               ,sheet = '2026 top 1850')

p00 = readr::read_csv('bartovik//0 inputs//prospects2.csv'
              ,skip=77) %>% 
  select(1:46)

# diff=setdiff(b0, p00)

p1 = p00 %>% 
  #split would work but Sep issue
  # seperate(`...30`, into = c('') %>% ) %>% 
  mutate(
     height = case_when(
 `...4` == 'Jun-00' ~ '6-0'
 ,`...4` == 'Jul-00' ~ '7-0'
 ,str_detect(`...4`
            ,"\\d+-[A-Za-z]{3}$") ~ paste(
                                  match(str_extract(`...4`, "[A-Za-z]{3}$"), month.abb),
                                        str_extract(`...4`, "^\\d+"),
                                        sep = "-"
                                          )
            ,TRUE ~ as.character(`...4`))
    ,Dunks = if_else(
      str_detect(Dunks, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(Dunks, "[A-Za-z]{3}$"), month.abb),
        str_extract(Dunks, "^\\d+"),
        sep = "-"
        ),Dunks)
   ,`close_2P` =  if_else(
      str_detect(`Close 2`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`Close 2`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`Close 2`, "^\\d+"),
        sep = "-"
        ),`Close 2`)
   ,`far_2P` =  if_else(
      str_detect(str_trim(`Far 2`), "^(\\d+-[A-Za-z]{3}|[A-Za-z]{3}-\\d+)$"),
      paste(
        match(str_extract(`Far 2`, "[A-Za-z]{3}"), month.abb),
        str_extract(`Far 2`, "\\d+"),
        sep = "-"
        ),`Far 2`)
   ,FT =  if_else(
      str_detect(`FT`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`FT`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`FT`, "^\\d+"),
        sep = "-"
        ),`FT`)
   ,`2P` = if_else(
      str_detect(`2P`, "\\d+-[A-Za-z]{3}$"),
      paste(
        match(str_extract(`2P`, "[A-Za-z]{3}$"), month.abb),
        str_extract(`2P`, "^\\d+"),
        sep = "-"
        ),`2P`)
   ,`3P` = if_else(
     #if find #-3letters OR 3letters-#
      str_detect(str_trim(`3P`), "^(\\d+-[A-Za-z]{3}|[A-Za-z]{3}-\\d+)$"),
      paste(
        #get the Jan, then switch it with 1
        match(str_extract(`3P`, "[A-Za-z]{3}"), month.abb),
        #get the digit or 2
        str_extract(`3P`, "\\d+"),
        sep = "-"
      ),`3P`)
        ) %>% 
  separate(Dunks, into = c('Dunks_m', 'Dunks_a'),sep='-') %>% 
separate(`2P`, into = c('2PM', '2PA'),sep='-') %>% 
separate(`close_2P`, into = c('close_2PM', 'close_2PA'),sep='-')  %>% 
separate(`far_2P`, into = c('far_2PM', 'far_2PA'),sep='-') %>% 
separate(`FT`, into = c('FTM', 'FTA'),sep='-') %>% 
separate(`3P`, into = c('3PM', '3PA'),sep='-') #%>% 
  select(-c('...4') # 'Close 2', 'Far 2', 'FT', '2P', '3P')) %>%
  # rename('3P/100'='3PR', '3PR'='...38')

 p2 = p1 %>% 
  rename(class = Player, Player='...5') %>% 
  # select(-Year) %>%
  mutate(across(c(28:Reb, close_2PM:far_2PA), as.numeric)) %>% 
  separate(Player, into = c('player', 'stats_yr'),sep='\\(') %>% 
  mutate(
    stats_yr = sub("\\)", "", stats_yr)
    ,player = str_trim(player)
    ,stock_pct = Blk+Stl
   ,`2P_pct` = `2PM`/`2PA`
   ,close_2P_pct = close_2PM/close_2PA
   ,far_2P_pct = far_2PM/far_2PA
   ,`3P_pct` = `3PM`/`3PA`
     ,`FT_pct` = `FTM`/`FTA`
         )
p3 = p2 %>% 
  mutate(stats_yr = paste0('20',stats_yr)) %>% 
  #cant believe i left age out of b0
  select(Rk,
         ,stats_yr
         ,player, class, Team ,Conf
         , Pick, height,Role,G
         ,9:20
         , Ast_pct = 'Ast...22'
         , 22:25, stock_pct, 'FC/40'
         ,'2PM','2PA', '2P_pct'
         ,'Dunks_m',
         ,'close_2PM','close_2PA', 'close_2P_pct'
         ,'far_2PM','far_2PA', 'far_2P_pct'
         ,'3PM','3PA', '3P_pct'
         ,'FTM','FTA', 'FT_pct'
         ,'3PR', Pts='3P/100'
         ,Ast='Ast...43', Reb
         )

p3_yrs = p3 %>% 
  group_by(player, Pick, height) %>% 
  mutate(draft_yr = max(stats_yr)) %>% 
  ungroup() %>% 
  relocate(draft_yr, .before=Pick) %>% relocate(stats_yr, .before=G)

p4_yrs = p3_yrs %>% 
  mutate(Pick = as.numeric(Pick)
         ,draft_yr = as.double(draft_yr)
         ,stats_yr = as.double(stats_yr)
         )

writexl::write_xlsx(p4_yrs, 'bartovik\\1 outputs\\26 torvik cleaned.xlsx')

```

#bind

```{r}
bp = bind_rows(b3_yrs, p4_yrs) %>% distinct()
writexl::write_xlsx(p4_yrs, 'bartovik\\1 outputs\\torvik plus 26.xlsx')

```

